version: '3.7'

services:
  postgres:
    image: postgres:14.5-alpine3.16
    container_name: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: API.Dockerfile
    container_name: bank-api
    ports:
      - '8080:8080'
    environment:
      - DB_SOURCE=$DB_SOURCE
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint:
      [
        "/app/wait-for.sh",
        "postgres:5432",
        "--",
        "/app/start.sh"
      ]
    command: [ "/app/main" ]

volumes: {}

networks: {}