version: '3.7'
services:
  postgres:
    image: postgres:14.5-alpine3.16
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=goBank
  gobank-api:
    build:
      context: .
    container_name: gobank-api
    ports:
      - '8080:8080'
      - '9090:9090'
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/goBank?sslmode=disable
    depends_on:
      - postgres
    entrypoint:
      [
        "/app/wait-for.sh",
        "postgres:5432",
        "--",
        "/app/start.sh"
      ]
    command: [ "/app/main" ]

volumes: {}

networks: {}

secrets: {}