version: '3.7'

services:
  postgres:
    container_name: postgres
    build:
      context: postgres
    restart: always
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - '5432:5432'

volumes: {}

networks: {}